server:
 port: 8888
spring:
 datasource:
  username: root
  password: 123456
  url: jdbc:mysql://localhost:3306/jd
  driverClassName: com.mysql.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource